package database;

import java.sql.*;

public class CreateTableDB {

    public void createTable() {

        Connection con = null;
        Statement stmt = null;


        try {
            Class.forName("org.hsqldb.jdbc.JDBCDriver");
            con = DriverManager.getConnection("jdbc:hsqldb:hsql://localhost/workdb", "SA","");


            TableExistOrNot tableExistOrNot = new TableExistOrNot();
            boolean result = tableExistOrNot.tableExist(con, "users");

            String sql = "CREATE TABLE users (id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY , Username VARCHAR(30) NOT NULL, E_mail VARCHAR(50) NOT NULL, Password VARCHAR(50) NOT NULL, Premium BIT DEFAULT 0, Administrator BIT DEFAULT 0)";
            stmt = con.createStatement();

            if(result) {
                System.out.println("exist");
            } else {
                stmt.executeUpdate(sql);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
